version: '3.8'

services:
  mysqldb-jwt-auth:
    container_name: mysql-jwt-auth
    image: mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    volumes:
      - ${PC_DATABASE_PATH}:${CONTAINER_PATH}

  app:
    container_name: app
    depends_on:
      - mysqldb-jwt-auth
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    env_file: ./.env
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    environment:
      SPRING_APPLICATION_JSON: '{
                "spring.datasource.driver-class-name": "com.mysql.cj.jdbc.Driver",
                "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQLDialect",
                "spring.datasource.url": "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?allowPublicKeyRetrieval=TRUE",
                "spring.datasource.username": "$MYSQLDB_USER",
                "spring.datasource.password": "$MYSQLDB_ROOT_PASSWORD",
                "spring.jpa.show-sql": "true",
                "spring.jpa.hibernate.ddl-auto": "update"
            }'
    stdin_open: true
    tty: true